### ISSUE TITLE
用Samples里Rice.model3.json 时崩溃

### ISSUE THREAD

**Issue by Suigc** [Arisego/UnrealLive2D#2]
崩在ModelRenders_DrawableMask.cpp的   217行 
check(!tb_InvertMask);

看注释是还没处理tb_InvertMask 为true的情况，希望作者大大能予以修复

**Comment by Arisego** [comment]
这个功能当时不知道哪个模型有使用所以没有实现呢。
找到时间的话会进行更新。

**Comment by Arisego** [comment]
已添加支持。

**Comment by Suigc** [comment]
感谢！
