### ISSUE TITLE
load motions by button on clicked

### ISSUE THREAD

**Issue by AA-Developer** [Arisego/UnrealLive2D#3]
Hello
First, I thank you for making this work possible load live2d in ue4
Almost everything is ready, except
A feature that I cannot handle whatever I try

They is load motions by button on clicked
Is this possible
if yes, can you give me a picture for blueprint?
if no,Do you have any way to help me do this?

**Comment by Arisego** [comment]
Do you mean play different motion by click button?
Now the motion control logic is in function `FRawModel::OnUpdate`, it just call `StartRandomMotion` after one motion ends. You can inject your logic here and link the control to blueprint.

**Comment by Arisego** [comment]
I add some simple motion control logic for sample in the new version of plugin. It may help you build your own control logic on motion control.
