### ISSUE TITLE
Crash when using custom Live2d assets

### ISSUE THREAD

**Issue by kprimo** [Arisego/UnrealLive2D#4]
大佬好，我在成功编译插件后每次加载自己制作的模型或是网上的一些模型均会Crash（可以导入但不能查看、不能使用）

Crash信息如下

`LoginId:9922ef794db312b81c214cb0d485242a
EpicAccountId:94ac6b12eedd470bad977646c14d6539

Unhandled exception

UE4Editor_Cubism!csmUpdateAnimationUserDataCallbackUpdate() [d:\unreal packages\live2d\zipme\plugins\livv\source\cubism\private\framework\src\animationuserdatacallback.c:42]
UE4Editor_Cubism!UCubismViewer::UpdateCsm() [d:\unreal packages\live2d\zipme\plugins\livv\source\cubism\private\cubsimviewer.cpp:431]
UE4Editor_Cubism!UCubismViewer::Tick() [d:\unreal packages\live2d\zipme\plugins\livv\source\cubism\private\cubsimviewer.cpp:301]
UE4Editor_Engine
UE4Editor_UnrealEd
UE4Editor_UnrealEd
UE4Editor
UE4Editor
UE4Editor
UE4Editor
UE4Editor
kernel32
ntdll`

使用UE4.22版本编译

**Comment by Arisego** [comment]
从log上看你似乎使用的是旧版本的livv的插件，旧版本使用的是很旧的CubismSDK，可能已经无法兼容新的live2d模型。建议用最新版本的插件加载测试~
